### ISSUE TITLE
Teacher crawler for taro crashes

### ISSUE THREAD

**Issue by Belissimo-T** [ArtrenH/VPlan_FR#195]
```pytb
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/programming/VPlan_FR/backend/load_plans.py", line 155, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/programming/VPlan_FR/backend/load_plans.py", line 140, in main
    await asyncio.gather(
  File "/root/programming/VPlan_FR/backend/load_plans.py", line 27, in check_infinite
    self.plan_processor.update_all()
  File "/root/programming/VPlan_FR/backend/plan_processor.py", line 253, in update_all
    self.update_meta()
  File "/root/programming/VPlan_FR/backend/plan_processor.py", line 160, in update_meta
    self.scrape_teachers()
  File "/root/programming/VPlan_FR/backend/plan_processor.py", line 176, in scrape_teachers
    _scraped_teachers = schools.teacher_scrapers[str(self.school_number)]()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/programming/VPlan_FR/backend/schools/taro.py", line 21, in get_teachers
    if teacher_data[1] and teacher_data[2]:
       ~~~~~~~~~~~~^^^
IndexError: list index out of range

```

**Comment by ArtrenH** [comment]
fixed with 6223133274e7d3a8f4821b2d56709eb46e3ae7f7
